const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE || undefined,headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:412,height:915},deviceScaleFactor:1});let errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:8765');await page.getByText('Explorer une cave d’exemple').click();assert.equal(await page.evaluate(()=>state.wines.reduce((n,w)=>n+M.qty(w),0)),13);assert.equal(await page.locator('#app').innerText().then(t=>t.includes('€')),false);await page.screenshot({path:'out/01-cave-reelle.png',fullPage:true});
await page.getByRole('button',{name:'▦ Casiers',exact:true}).click();await page.reload();assert.equal(await page.evaluate(()=>state.settings.view),'plan');await page.getByRole('button',{name:'A1, 6 bouteilles',exact:true}).click();await page.getByRole('button',{name:/Saint-Émilion/}).click();await page.getByRole('button',{name:'− Retirer',exact:true}).click();await page.locator('#n').fill('2');await page.getByRole('button',{name:'Confirmer',exact:true}).click();assert.equal(await page.evaluate(()=>M.qty(state.wines[0])),4);
await page.getByRole('button',{name:'Déplacer',exact:true}).click();await page.locator('#n').fill('2');const next=await page.evaluate(()=>state.racks[0].cells[1].id);await page.locator('#to').selectOption(next);await page.getByRole('button',{name:'Confirmer',exact:true}).click();assert.equal(await page.evaluate(()=>M.qty(state.wines[0])),4);assert.equal(await page.evaluate(()=>state.wines[0].allocations.length),2);await page.screenshot({path:'out/02-fiche-vin.png'});
await page.getByRole('button',{name:'Fermer',exact:true}).click();await page.getByRole('button',{name:/Réglages/}).click();await page.getByLabel('Afficher les montants en euros').check();assert.equal(await page.evaluate(()=>state.settings.money),true);await page.getByRole('button',{name:'▦ Cave',exact:true}).click();assert((await page.locator('#app').innerText()).includes('€'));
await page.getByRole('button',{name:'Modifier',exact:true}).click();await page.locator('#rows').fill('1');await page.locator('#cols').fill('1');await page.getByRole('button',{name:'Enregistrer le rangement'}).click();assert.equal(await page.evaluate(()=>state.racks[0].cells.length),12);await page.getByRole('button',{name:'Fermer',exact:true}).click();
await page.getByRole('button',{name:'+ Ajouter un vin',exact:true}).click();await page.locator('#name').fill('Essai personnel');await page.locator('#quantity').fill('5');await page.locator('#notes').fill('À ouvrir en famille');await page.locator('#drinkFrom').fill('2027');await page.locator('#drinkTo').fill('2030');await page.getByRole('button',{name:'Enregistrer la fiche'}).click();assert.equal(await page.evaluate(()=>stockAt('unplaced')),5);await page.getByRole('button',{name:'Fermer',exact:true}).click();
// Export and restoration retain all information, including photos.
const downloadPromise=page.waitForEvent('download');await page.evaluate(()=>exportBackup());const dl=await downloadPromise;await dl.saveAs(path.resolve('tests/backup.json'));await page.evaluate(()=>{state.wines=[];save();render()});await page.getByRole('button',{name:/Réglages/}).click();await page.locator('#import-file').setInputFiles(path.resolve('tests/backup.json'));await page.waitForFunction(()=>state.wines.length===4);assert.equal(await page.evaluate(()=>stockAt('unplaced')),5);
// OCR reads a known image, locally, and proposes editable fields.
await page.getByRole('button',{name:'+ Ajouter un vin',exact:true}).click();await page.locator('#wine-form input[type=file]').first().setInputFiles(path.resolve('tests/label.jpg'));await page.waitForFunction(()=>wineDraft.photo.length>0);await page.getByRole('button',{name:'Créer la fiche depuis les photos',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#ocr-status').textContent.startsWith('Texte proposé'),{},{timeout:90000});assert.equal(await page.locator('#year').inputValue(),'2020');assert((await page.locator('#name').inputValue()).includes('BELLEVUE'));await page.screenshot({path:'out/03-lecture-etiquette.png'});await page.getByRole('button',{name:'Enregistrer la fiche'}).click();assert.equal(await page.evaluate(()=>state.wines.length),5);await page.reload();assert.equal(await page.evaluate(()=>state.wines.length),5);assert((await page.evaluate(()=>state.wines[4].photo.length))>1000);
assert.deepEqual(errors,[]);console.log('PASS UI: 2 vues, prix masqués/affichés, persistance, retrait, déplacement, réduction protégée, ajout, sauvegarde/restauration, OCR millésime 2020 et nom, photo persistée.');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
