package fr.macave.test;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.webkit.*;import android.util.AtomicFile;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;
public class MainActivity extends Activity {
 WebView web; ServerSocket server; String origin,base; volatile boolean running=true; ValueCallback<Uri[]> chooser; Uri cameraUri; String exportData; ExecutorService pool=Executors.newFixedThreadPool(3); AtomicFile store;
 @Override public void onCreate(Bundle b){super.onCreate(b);store=new AtomicFile(new File(getFilesDir(),"cave.json"));try{server=new ServerSocket(0,16,InetAddress.getByName("127.0.0.1"));origin="http://127.0.0.1:"+server.getLocalPort();base=origin+"/"+UUID.randomUUID().toString()+"/";new Thread(()->{while(running)try{final Socket s=server.accept();pool.execute(()->serve(s));}catch(Exception e){}}).start();}catch(Exception e){new AlertDialog.Builder(this).setMessage("Impossible de démarrer l’application : "+e.getMessage()).show();return;}
 web=new WebView(this);web.setBackgroundColor(Color.rgb(247,243,236));web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.getSettings().setSupportMultipleWindows(false);web.addJavascriptInterface(new Bridge(),"Native");web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return !r.getUrl().toString().startsWith(base);}@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){String u=r.getUrl().toString();if(u.startsWith(base)||u.startsWith("blob:")||u.startsWith("data:"))return null;return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));}});
 web.setWebChromeClient(new WebChromeClient(){@Override public boolean onJsAlert(WebView v,String u,String msg,JsResult result){new AlertDialog.Builder(MainActivity.this).setMessage(msg).setPositiveButton("OK",(d,w)->result.confirm()).setOnCancelListener(d->result.cancel()).show();return true;}@Override public boolean onJsConfirm(WebView v,String u,String msg,JsResult result){new AlertDialog.Builder(MainActivity.this).setMessage(msg).setPositiveButton("Confirmer",(d,w)->result.confirm()).setNegativeButton("Annuler",(d,w)->result.cancel()).setOnCancelListener(d->result.cancel()).show();return true;}@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> callback,FileChooserParams p){if(chooser!=null)chooser.onReceiveValue(null);chooser=callback;try{if(p.isCaptureEnabled()){String token=UUID.randomUUID().toString();cameraUri=Uri.parse("content://fr.macave.test.photos/"+token+".jpg");Intent i=new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(android.provider.MediaStore.EXTRA_OUTPUT,cameraUri);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);i.setClipData(ClipData.newRawUri("photo",cameraUri));startActivityForResult(i,21);}else{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);String[] types=p.getAcceptTypes();i.setType(types.length>0&&types[0].contains("image")?"image/*":"*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,p.getMode()==FileChooserParams.MODE_OPEN_MULTIPLE);startActivityForResult(i,20);}}catch(Exception e){chooser.onReceiveValue(null);chooser=null;Toast.makeText(MainActivity.this,"Sélecteur indisponible. Utilisez une photo déjà enregistrée.",Toast.LENGTH_LONG).show();}return true;}});
 android.widget.FrameLayout root=new android.widget.FrameLayout(this);root.setBackgroundColor(Color.rgb(247,243,236));root.addView(web);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});setContentView(root);web.loadUrl(base+"index.html");}
 void serve(Socket s){try{ s.setSoTimeout(10000);BufferedReader reader=new BufferedReader(new InputStreamReader(s.getInputStream(),"UTF-8"));String first=reader.readLine();if(first==null)return;String[] parts=first.split(" ");if(parts.length<2)return;String line;int headers=0;while((line=reader.readLine())!=null&&!line.isEmpty()){if(++headers>100)return;}String prefix=Uri.parse(base).getPath();String path=URLDecoder.decode(parts[1].split("\\?")[0],"UTF-8");if(!path.startsWith(prefix)||path.contains("..")||!parts[0].equals("GET")){respond(s,403,"text/plain",new byte[0]);return;}path=path.substring(prefix.length());if(path.isEmpty())path="index.html";String mime=path.endsWith(".html")?"text/html; charset=utf-8":path.endsWith(".css")?"text/css":path.endsWith(".js")?"application/javascript":path.endsWith(".wasm")?"application/wasm":"application/octet-stream";try(InputStream in=getAssets().open(path)){respond(s,200,mime,readBytes(in,30000000));}catch(IOException e){respond(s,404,"text/plain",new byte[0]);}}catch(Exception e){}finally{try{s.close();}catch(Exception e){}}}
 void respond(Socket s,int code,String mime,byte[] data)throws IOException{OutputStream out=s.getOutputStream();String h="HTTP/1.1 "+code+" OK\r\nContent-Type: "+mime+"\r\nContent-Length: "+data.length+"\r\nCache-Control: no-store\r\nX-Content-Type-Options: nosniff\r\nConnection: close\r\n\r\n";out.write(h.getBytes("UTF-8"));out.write(data);out.flush();}
 static byte[] readBytes(InputStream in,int max)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[16384];int n;while((n=in.read(buf))!=-1){if(out.size()+n>max)throw new IOException("Fichier trop volumineux");out.write(buf,0,n);}return out.toByteArray();}
 public class Bridge {@JavascriptInterface public synchronized String load(){try{return new String(store.readFully(),"UTF-8");}catch(FileNotFoundException e){return "";}catch(Exception e){return "{invalid";}}@JavascriptInterface public synchronized String save(String data){FileOutputStream out=null;try{if(data.length()>60000000)return "Cave trop volumineuse : exportez une sauvegarde.";new JSONObject(data);out=store.startWrite();out.write(data.getBytes("UTF-8"));store.finishWrite(out);return "";}catch(Exception e){if(out!=null)store.failWrite(out);return "Enregistrement impossible : "+e.getMessage();}}@JavascriptInterface public void exportFile(String data,String name){runOnUiThread(()->{if(exportData!=null){Toast.makeText(MainActivity.this,"Un export est déjà en cours.",Toast.LENGTH_SHORT).show();return;}exportData=data;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,name);try{startActivityForResult(i,30);}catch(Exception e){exportData=null;notifyJs("Export indisponible.");}});}}
 void notifyJs(String message){runOnUiThread(()->web.evaluateJavascript("toast("+JSONObject.quote(message)+")",null));}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==20||req==21){if(chooser==null)return;ArrayList<Uri> uris=new ArrayList<>();if(result==RESULT_OK){if(req==21&&cameraUri!=null)uris.add(cameraUri);else if(data!=null){if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount();i++)uris.add(data.getClipData().getItemAt(i).getUri());}else if(data.getData()!=null)uris.add(data.getData());}}chooser.onReceiveValue(uris.isEmpty()?null:uris.toArray(new Uri[0]));chooser=null;cameraUri=null;}else if(req==30){String content=exportData;exportData=null;if(result==RESULT_OK&&data!=null&&data.getData()!=null&&content!=null){Uri uri=data.getData();pool.execute(()->{try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){out.write(content.getBytes("UTF-8"));notifyJs("Sauvegarde exportée.");}catch(Exception e){notifyJs("Export échoué : "+e.getMessage());}});}}}
 @Override public void onBackPressed(){if(web==null){super.onBackPressed();return;}web.evaluateJavascript("goBack()",v->{if(!"true".equals(v))new AlertDialog.Builder(this).setMessage("Quitter Ma Cave ? Vos modifications sont enregistrées.").setPositiveButton("Quitter",(d,w)->finish()).setNegativeButton("Rester",null).show();});}
 @Override protected void onDestroy(){running=false;try{if(server!=null)server.close();}catch(Exception e){}pool.shutdown();if(web!=null)web.destroy();super.onDestroy();}
}
